name: Docs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install doxygen graphviz -y
      - run: doxygen Doxyfile
      - uses: actions/upload-artifact@v2
        with:
          name: doxygen-docs
          path: docs
